# Generated by Django 4.2.7 on 2023-11-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=100)),
                ('company_type', models.CharField(choices=[('Tech', 'Computer'), ('Non Tech', 'Mobile Centre'), ('Non Tech', 'Call Centre'), ('Tech', 'Networking')], max_length=50)),
                ('company_about', models.TextField(max_length=200)),
            ],
        ),
    ]
